version: "3.8"

services:
    frontend:
        container_name: frontend
        image: staticfloat/nginx-certbot
        depends_on: 
            - backend
        ports: 
            - "80:80"
            - "443:443"
        environment: 
            - NGINX_PORT=80
            - CERTBOT_EMAIL=iscnsysu2019@gmail.com
        volumes:
            - "./frontend/data/nginx/log:/var/log/nginx"
            - "./nginx:/etc/nginx/user.conf.d:ro"
            - "./html/:/usr/share/nginx/html:ro"
            - "letsencrypt:/etc/letsencrypt"
        restart: unless-stopped
        networks: 
            - backend

    # mongo:
    #     image: mongo:bionic
    #     environment:
    #         # - MONGO_INITDB_DATABASE=
    #         # - MONGO_INITDB_ROOT_USERNAME=
    #         # - MONGO_INITDB_ROOT_PASSWORD=
    #     restart: unless-stopped

    backend:
        container_name: manager
        build: backend/
        depends_on: 
            - vpn0
            - vpn1
            - vpn2
            # - mongo
        environment:
            # - MONGODB_URL=mongo
            # - MONGODB_ACCOUNT=
            - REGNUM=3
        restart: unless-stopped
        networks: 
            - backend
            - frontend
            - vpn

    vpn0:
        container_name: vpn0
        build: vpn/
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PEERS=105
        volumes:
            - ./data/vpn1/config:/config
        ports: 
            - 140.117.169.211:51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        networks: 
            - vpn
    
    vpn1:
        container_name: vpn1
        build: vpn/
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PEERS=105
        volumes:
            - ./data/vpn2/config:/config
        ports: 
            - 140.117.169.212:51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        networks: 
            - vpn
    
    vpn2:
        container_name: vpn2
        build: vpn/
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PEERS=105
        volumes:
            - ./data/vpn3/config:/config
        ports: 
            - 140.117.169.213:51820:51820/udp
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
        networks: 
            - vpn

networks: 
    backend:
        driver: bridge
    frontend:
        driver: bridge
    vpn:
        driver: bridge
volumes:
    letsencrypt: